# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

matrix_multiplication <- function(n, A) {
    .Call('vertexCA_matrix_multiplication', PACKAGE = 'vertexCA', n, A)
}

convolveCpp <- function(a, b) {
    .Call('vertexCA_convolveCpp', PACKAGE = 'vertexCA', a, b)
}

timesTwo <- function(x) {
    .Call('vertexCA_timesTwo', PACKAGE = 'vertexCA', x)
}

